apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    env: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: qas
  labels:
    env: qas
---
apiVersion: v1
kind: Namespace
metadata:
  name: prd
  labels:
    env: prd
