apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    env: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: qas
  labels:
    env: qas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
  namespace: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  labels:
    app: backend2
  namespace: qas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
